### ISSUE TITLE
Patch some value for a property who has null value will throw exception

### ISSUE THREAD

**Issue by jwobbe** [OData/RESTier#363] opened 2016-04-12 18:24 UTC
[This Issue](https://github.com/OData/RESTier/issues/269) seems to be back.  Same cause and symptom.

**Comment by jwobbe** [comment] 2016-04-12 18:30
I should have mentioned that I'm not sure when it was reintroduced, but it can be found in commit [38ab2f0](https://github.com/OData/RESTier/commit/d09cef0507be2fdcab6f754e79fab465aaaa7ee5) and based on subsequent commit details, it likely exists in the latest commit as well.

**Comment by chinadragon0515** [comment] 2016-04-13 00:33
@jwobbe I did some investigation of the issues, three questions for you,
1. Can I know the exception stack you got now?
2. How you create your API? Do you use ApiBase directly or use DbApi?
3. Which version you are using now?

**Comment by chinadragon0515** [comment] 2016-04-13 00:36
Some findings with newest code,
1. DbApi has no issue, it works well to path property which has null value. Need to add test cases.
2. For ApiBase, first will see the issue of change set preparer is not set, exception like 
 "message":"Change set preparer is missing.","type":"System.NotSupportedException","stacktrace":" at Microsoft.Restier.Core.Submit.DefaultSubmitHandler.d__0.MoveNext() in D:\\dev\\githome\\RESTier.vin\\src\\Microsoft.Restier.Core\\Submit\\DefaultSubmitHandler.cs:line 41\r\n

After make changes of this, find entity is not set and is null (For DbAPi, this is set during change set preparation).
"message":"Object reference not set to an instance of an object.","type":"System.NullReferenceException","stacktrace":" at Microsoft.Restier.Core.Conventions.ConventionBasedChangeSetEntryValidator.ValidateEntityAsync(SubmitContext context, ChangeSetEntry entry, ValidationResults validationResults, CancellationToken cancellationToken) in D:\\dev\\githome\\RESTier.vin\\src\\Microsoft.Restier.Core\\Conventions\\ConventionBasedChangeSetEntryValidator.cs:line 36\r\n at Microsoft.Restier.Core.Submit.DefaultSubmitHandler.d__4.MoveNext() in D:\\dev\\githome\\RESTier.vin\\src\\Microsoft.Restier.Core\\Submit\\DefaultSubmitHandler.cs:line 166\r\n--- 

Still investigation whether the issue is always there or introduce by some new changes.

**Comment by jwobbe** [comment] 2016-04-14 15:23
I don't think that it's just limited to ApiBase.  Here's my entire API class:
public class CoreEntitiesApi : DbApi<CoreEntities>    {    }

Here's the stacktrace:
 at Microsoft.Restier.EntityFramework.Submit.ChangeSetPreparer.SetValues(DbEntityEntry dbEntry, DataModificationEntry entry, Type entityType)
   at Microsoft.Restier.EntityFramework.Submit.ChangeSetPreparer.<PrepareAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Restier.Core.Submit.DefaultSubmitHandler.<SubmitAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Restier.Core.ApiContextExtensions.<SubmitAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Restier.WebApi.RestierController.<Update>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Restier.WebApi.RestierController.<Patch>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

**Comment by jwobbe** [comment] 2016-04-14 15:46
I'm able to reproduce this issue with the latest 0.5.0-beta version from github.

**Comment by chinadragon0515** [comment] 2016-04-18 01:27
@jwobbe I cannot reproduce this with newest code of DbApi, several questions,
1. We have not released 0.5.0-beta yet, can I know how you refer to this version? Do you build by yourself? can you show me your package.config file?
2. Can I know what's the property type been patch with null? Is it primitive type or complex type or complex type collection or others? If you can show me metadata and request, that will be helpful.

**Comment by jwobbe** [comment] 2016-04-18 18:11
RE 1: I built 0.5.0-beta myself from the git source because 0.4.0-rc2 has a major bug (long as entity key) that prevented me from using it.  The binaries are on our internal nuget server and pulled in as with the package id of "Microsoft.Restier.CustomBuild".  Here's my package.config:

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.4.1.9004" targetFramework="net46" />
  <package id="EntityFramework" version="6.1.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.OData" version="5.9.0" targetFramework="net46" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net46" />
  <package id="Microsoft.Extensions.DependencyInjection" version="1.0.0-rc1-final" targetFramework="net46" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="1.0.0-rc1-final" targetFramework="net46" />
  <package id="Microsoft.OData.Client" version="6.15.0" targetFramework="net46" />
  <package id="Microsoft.OData.Core" version="6.15.0" targetFramework="net46" />
  <package id="Microsoft.OData.Edm" version="6.15.0" targetFramework="net46" />
  <package id="Microsoft.Restier.CustomBuild" version="0.5.0.0-beta" targetFramework="net46" />
  <package id="Microsoft.Spatial" version="6.15.0" targetFramework="net46" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net46" />
  <package id="Newtonsoft.Json" version="8.0.2" targetFramework="net46" />
  <package id="Ninject" version="3.2.2.0" targetFramework="net46" />
  <package id="Ninject.Extensions.Wcf" version="3.2.2.0" targetFramework="net46" />
  <package id="Ninject.Web.Common" version="3.2.3.0" targetFramework="net46" />
  <package id="OctoPack" version="3.0.46" targetFramework="net46" developmentDependency="true" />
  <package id="Oracle.ManagedDataAccess" version="12.1.2400" targetFramework="net46" />
  <package id="Oracle.ManagedDataAccess.EntityFramework" version="12.1.2400" targetFramework="net46" />
  <package id="WebGrease" version="1.5.2" targetFramework="net46" />
</packages>

RE 2: The property type being patched is a string mapped to a varchar.

**Comment by chinadragon0515** [comment] 2016-04-19 05:23
@jwobbe  thanks for your information.
1. I recheck, and still can not reproduce. You can get all restier code and run the Microsoft.Restier.WebApi.Test.Services.Trippin project, then issue a patch request to URL like http://localhost:18384/api/Trippin/People(7) with request body like "{ "FirstName":"u4","LastName":null }"
There is no issues.

2. I will suggest you rebuild a package from newest code and have a test.

3. If you can create a simple project with the package your build and can reproduce the issue, I will take a look.

thanks.

**Comment by jwobbe** [comment] 2016-04-19 19:01
This is easily reproducible in the Trippin test project.  Update any person who's LastName property is null before the update.  The following yields the same exception:

<FiddlerRaw>
PATCH http://localhost:18384/api/Trippin/People(3) HTTP/1.1
OData-Version: 4.0
OData-MaxVersion: 4.0
Content-Type: application/json;odata.metadata=minimal
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
User-Agent: Microsoft ADO.NET Data Services
Host: localhost:18384
Content-Length: 19
Expect: 100-continue

{"LastName":"abc" }
</FiddlerRaw>

The same patch to any person who's LastName property is not null succeeds.

**Comment by chinadragon0515** [comment] 2016-04-20 02:35
OK, I can re-produce the issue now.
The issue is when we patch some value for a property who has null value now, it will throw exception.

The related issue is when we patch null for a property, it will throw exception.

So they are two different issues.

**Comment by chinadragon0515** [comment] 2016-04-20 03:50
@jwobbe I have merged a fix, you can try with newest code, any issues, help to let us know.

**Closed by chinadragon0515** 2016-04-20 03:50 UTC
Labels: in progress
