### ISSUE TITLE
The `master` branch and the latest CI builds are not same

### ISSUE THREAD

**Issue by cilerler** [OData/RESTier#691] opened 2021-08-11 14:18 UTC
The following code block commented on the NuGet package and made me question what else is different from the master.
https://github.com/OData/RESTier/blob/38b8de60c0e7169f31e88872bc4e1313f754080a/src/Microsoft.Restier.EntityFramework.Shared/Extensions/RestierEntityFrameworkServiceCollectionExtensions.cs#L58-L85

### Reproduction steps

Replace this line https://github.com/OData/RESTier/blob/38b8de60c0e7169f31e88872bc4e1313f754080a/src/Microsoft.Restier.Samples.Northwind.AspNetCore/Microsoft.Restier.Samples.Northwind.AspNetCore.csproj#L24

with line below

```xml
<PackageReference Include="Microsoft.Restier.EntityFrameworkCore" Version="1.0.0-CI-20210719-021012" />
```

And you will see that `.UseSqlServer()` part  https://github.com/OData/RESTier/blob/38b8de60c0e7169f31e88872bc4e1313f754080a/src/Microsoft.Restier.Samples.Northwind.AspNetCore/Startup.cs#L50 is not working.

CC: @robertmclaws @mikepizzo 
Not sure who is JHC, but please don't let anyone change anything outside of the repository.

**Comment by robertmclaws** [comment] 2021-08-11 15:32
Hi @cilerler. Appreciate your opinion on how the project should be run, however we believe the structure is presently being run under best practices, given the circumstances:

1) We have already shipped 6 Release Candidates. Those are presently being mapped to the `main` branch,
2) We are working on adding .NET 5 support under multiple configurations in the [breakdance-net5](https://github.com/OData/RESTier/tree/breakdance-net5) branch. This code has a number of errors in various configurations, and as such, is not yet a candidate for release, so it has not been merged into `main` yet.
3) The latest CI builds have been coming from the `breakdance-net5` branch, and will continue to do so until they are release-ready.
4) Because moving to the CI builds is technically a downgrade from the RC builds, this is the proper approach to ensure our customers do not experience any regressions.

We apologize if you feel this is in error, but it will be moot point soon, as we get the remaining unit tests resolved.

Thank you for your patience as we work to ship an amazing 1.0 release!

**Closed by robertmclaws** 2021-08-11 15:32 UTC
