### ISSUE TITLE
asp.net vnext ( RC1 ) and OWIN Support?

### ISSUE THREAD

**Issue by ChrisRichner** [OData/RESTier#256] opened 2015-11-11 19:47 UTC
Hi there,

we're using RESTier with great success in our current **classic** project. We'd loved to change gears and use the new project system that **asp.net vnext (beta8)** brings.

We found no way to port our existing project over to the new world because we failed to add RESTier to the OWIN Pipeline.

Is there have any kind of **OWIN** and / or **asp.net vnext** support with RESTier? Do you have a Roadmap?

Thanks!

**Comment by lewischeng-ms** [comment] 2015-11-12 06:27
@ChrisRichner Thanks very much for your positive feedback on RESTier! RESTier depends on OData Web API to support ASP.NET vNext. This could possibly be part of our roadmap in the next few months depending on the team resource.  For OWIN support, this is a brand-new **publisher** project for RESTier. We currently has no plan for it but we warmly welcome any community contribution on **OWIN publisher**.

**Comment by mikepizzo** [comment] 2017-06-10 04:17
Closing as duplicate of #464 (and others).

**Closed by mikepizzo** 2017-06-10 04:17 UTC
Labels: backlog, feature
