### ISSUE TITLE
[URL] RESTier does not support two TimeOfDay constants comparision

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/RESTier#130] opened 2015-07-21 06:03 UTC
Such as

```
http://localhost:18384/api/Trippin/Trips?$filter=07:59:59.999 eq 08:00:00.000
```

Currently will throw exception:

```
Unable to create a constant value of type 'Microsoft.OData.Edm.Library.TimeOfDay'. Only primitive types or enumeration types are supported in this context.
```

**Comment by chinadragon0515** [comment] 2016-04-21 00:51
This one works well

http://localhost:18384/api/Trippin/People?$filter=BirthTime%20eq%2022:58:02.0000000

**Comment by chinadragon0515** [comment] 2016-04-21 05:26
After more investigation,
1. TimeofDay property compare is already supported and there is test case there. Done by WebAPi ExpressionBinderBase.cs which covert the type to time ticks and compare.
2. The issue is when user uses filter with two TimeOfDay constant values as EF does not support this type.

The idea is in EF expression filter to convert TimeOfDay to TimeSpan, but now the constant value is type of TypedLinqParameterContainer<Microsoft.OData.Edm.Library.TimeOfDay> which is internal class, so the filter can not get the value and do the covert.

Move this to backlog again and will visit it when WebApi breaking changes is done.

**Comment by robertmclaws** [comment] 2019-07-03 15:53
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!

**Closed by robertmclaws** 2019-07-03 15:53 UTC
Labels: P4, feature, legacy
