### ISSUE TITLE
Consider using a hook handler (IQueryExecutor) in publisher (WebAPI) to process the TotalCount

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/RESTier#323] opened 2016-03-16 07:33 UTC
... as suggested by Mark.

Then this hook handler can call its inner handler which is typically the one from the provider.

**Comment by rayao** [comment] 2016-03-16 11:24
The problem is IQueryExecutor can't process ApiData based query, the input query must be processed by DefaultQueryHandler first.

**Comment by rayao** [comment] 2016-03-16 11:25
Oh do you mean add an IQueryExecutor implementation which call DefaultQueryHandler to translate the query, then call the inner provider IQueryExecutor?

**Comment by lewischeng-ms** [comment] 2016-03-16 12:10
@rayao, when RESTier calls the IQueryExecutor, the LINQ query has already been processed by the query pipeline (such as replacing ApiData, inspection, filtering, etc.) thus it should be ready to execute anyway. We just inject a query executor from Restier.WebApi to deal with "odata.count" (which is to send an additional count query) and then call the inner query executor. The good thing here is that we still save a lot of time from the count query because it does not need to go through the query pipeline again.

**Comment by lewischeng-ms** [comment] 2016-03-16 12:13
I know there could be some critical points we need to deal with but it could be a fairly good option which 1) moves the "odata.count" logic out of provider; 2) doesn't lower the performance much.

**Comment by rayao** [comment] 2016-03-16 12:15
Cool. Then perhaps we should ignore $top/skip/expand/count in WebApi, then in the WebApi QueryExecutor, generate 2 query base on the input query, 1 apply $top/skip/expand, the other 1 apply $count. Will that work?

**Comment by rayao** [comment] 2016-03-16 12:17
Let WebApi inject a service would be problematic under current design.

**Comment by lewischeng-ms** [comment] 2016-03-16 12:24
Yeah, there are a lot of benefit like these which we could possibly gain from this design. Again there are many things ahead that we need to work out. But it worths a try:-)

**Comment by rayao** [comment] 2016-03-23 07:52
Resolved by #329

**Closed by rayao** 2016-03-23 07:52 UTC
