### ISSUE TITLE
Enum filter value returns 404 for empty result set

### ISSUE THREAD

**Issue by magnumb** [OData/RESTier#554] opened 2017-03-10 18:42 UTC
When I filter an enum column, an empty result set returns a 404, "The request resource is not found," instead of a 200 with an empty array.

### Assemblies affected
RESTier 1.0.0-beta  

### Reproduce steps
http://localhost:5000/api/Items?%24filter=Status+eq+MyProject.Models.ItemStatus%27Enabled%27
{"error":{"code":"","message":"The request resource is not found."}}

### Expected result
{"@odata.context":"http://localhost:5000/api/$metadata#Items","value":[]}  

### Actual result
{"error":{"code":"","message":"The request resource is not found."}}

### Additional details
When I filter an integer column, an empty result set returns a 200 with an empty array as expected.

http://localhost:5000/api/Items?%24filter=ItemTypeId+eq+9999
{"@odata.context":"http://localhost:5000/api/$metadata#Items","value":[]}

**Comment by mateusz-malicki** [comment] 2017-05-19 08:07
I think that problem is more generic...
Enum reference is probably compiled to constant node in expression.
And constant nodes are a little no-noes for RESTier :)
You can observe same behaviour when constant node is used in OnFilter query.

**Comment by Tiberriver256** [comment] 2019-04-30 12:58
Yep, I'm getting this just filtering on regular properties. Is there any workaround?

**Comment by robertmclaws** [comment] 2019-07-03 16:28
We've encountered RESTier returning 404s for no results in other areas as well. I will try to address this for the 1.0 release.

**Comment by robertmclaws** [comment] 2019-07-03 19:27
Closing as a duplicate of #626, since that ticket has more details about where the problem lies in code.

**Closed by robertmclaws** 2019-07-03 19:27 UTC
Labels: P1, bug
